AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - bin/**/*

Lint/ScriptPermission:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/MethodLength:
  CountAsOne: ['array', 'hash']
