development:
  clients:
    default:
      database: mapping_service_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
test:
  clients:
    default:
      database: mapping_service_test
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
production:
  clients:
    default:
      database: mapping_service_production
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
