name: docker-image-build-and-push
run-name: Docker Image Build & Push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Tag Name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Buildah Build
        uses: redhat-actions/buildah-build@v2
        with:
          image:
          tags: ${{ env.RELEASE_VERSION }} latest
          containerfiles: |
            ./Containerfile
      - name: Log in to registry
        # This is where you will update the personal access token to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Push image (latest)
        run: docker push ghcr.io/rebelweb/mapping_service:latest
      - name: Push image
        run:  docker psuh ghcr.io/rebelweb/mapping_service:${{ env.RELEASE_VERSION }}
