name: docker-image-build-and-push
run-name: Docker Image Build & Push
on: [tag]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Tag Name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Log In To Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_KEY }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build Docker Image
        run: docker build  . --tag mapping_service
      - name: Tag Latest Image
        run: docker tag mapping_service ${{ secrets.DOCKER_HUB_USERNAME }}/mapping_service:latest
      - name: Tag Versioned Image
        run: docker tag mapping_service ${{ secrets.DOCKER_HUB_USERNAME }}/mapping_service:${{ env.RELEASE_VERSION }}
      - name: Push Latest Image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mapping_service:latest
      - name: Push Versioned Image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mapping_service:${{ env.RELEASE_VERSION }}
